### PR TITLE
Add Javadoc badge with automatic version detection

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by dmarkov** [comment]
@valery1707 Many thanks, I will find someone to review it before we merge

**Comment by dmarkov** [comment]
@yegor256 pull request is rather short, review it please

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 **16 mins** was added to your account, many thanks for your contribution (payment 000-a963b766)! The task took 26 hours and 36 mins.... you're getting extra minutes here (c=1)... added +16 to your rating, now it is equal to [+4514](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
