### PR TITLE
include system.properties and .env file

### PR DESCRIPTION
**Pull request by dtretter**
adds the system.properties and .env files from the projects basedir to target/heroku

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@dtretter are you planning to finish this?

**Comment by yegor256** [comment]
@dtretter I'm closing, it's too old and unmergeable. Don't hesitate to submit again

**Comment by dmarkov** [comment]
@yegor256 I added **20 mins** to your account, many thanks for working with the project! The completion time here was 000-dff2143a.. you're getting extra minutes here (c=5). +20 added to your rating, at the moment it is: [+12318](http://www.netbout.com/b/35008?open=rating)

**Pull request closed without merging**
