### PR TITLE
#4 - update copyright to 2015

### PR DESCRIPTION
**Pull request by nathansgreen**

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks, let me find someone who can review this pull request

**Comment by dmarkov** [comment]
@krzyk please review this one

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by dmarkov** [comment]
@krzyk Much obliged! I've added **16 mins** to your account in payment "50518801"... +16 added to your rating, current score is: [+2004](http://www.netbout.com/b/35035?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
